export const ALL_SLOTS = 'ALL_SLOTS'
export const ALL_SLOTS_SUCCESS = 'ALL_SLOTS_SUCCESS'
export const ADD_APPOINTMENT = 'ADD_APPOINTMENT'
export const ADD_APPOINTMENT_SUCCESS = 'ADD_APPOINTMENT_SUCCESS'
